version: 2.1
jobs:
  build:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   environment:
      GIT_EMAIL: 'hocinehot18@gmail.com'
      GIT_NAME: 'noob-eng'
      VERSION: '3.5'
      TWRP_MANIFEST: 'twrp-6.0'
      VENDOR: 'condor'
      DEVICE: 'PGN528'
 #     GITHUB_TOKEN: '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'
   steps:
      - run:
          command: |
           echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
           git config --global user.email "${GIT_EMAIL}"
           git config --global user.name "{GIT_NAME}"
           git config --global color.ui false
           repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b ${TWRP_MANIFEST}
           repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle --prune --optimized-fetch
           git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${DEVICE}
           export ALLOW_MISSING_DEPENDENCIES=true
           export LC_ALL=C
           source build/envsetup.sh
           lunch omni_${DEVICE}-eng
           mka recoveryimage -j$(nproc --all)
           export BUILDFILE_IMG=$(find $(pwd)/out/target/product/${DEVICE}/recovery.img 2>/dev/null)
           export UPLOAD_PATH=$(pwd)/out/target/product/${DEVICE}/upload/
           mkdir ${UPLOAD_PATH}
           cp $BUILDFILE_IMG $UPLOAD_PATH
           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Latest Release for $(echo $DEVICE)" -b "TWRP $(echo $VERSION)"  -c ${CIRCLE_SHA1} -delete ${VERSION} ${UPLOAD_PATH}
           

workflows:
  version: 2.1
  cooking:
    jobs:
      - build:
          context: hocine

